apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport-svc
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
   - name: http
     port: 80              #Nodeport service port
     targetPort: 80        #container/pod port
     nodePort: 3001        # Nodeport on which app would be published